[package]
name = "transceiver-decode"
version = "0.1.0"
edition = "2021"

[features]
api-traits = [ "dep:schemars", "dep:serde" ]

[dependencies]
transceiver-messages = { path = "../messages", features = [ "std" ] }
thiserror = "1"

[dependencies.schemars]
version = "0.8"
optional = true

[dependencies.serde]
version = "1"
optional = true

[dev-dependencies]
serde = "1"
serde_json = "1"
schemars = "0.8"
