[package]
name = "transceiver-messages"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1"

[dependencies.hubpack]
version = "0.1.0"

[dependencies.serde]
version = "1"
features = [ "derive" ]
default-features = false

[features]
std = []
default = [ "std" ]
